n = int(input('Digite um número: '))
print('O dobro de {} é {}'.format(n, n * 2))
print('O triplo de {} é {}'.format(n, n * 3))
print('A raiz quadrada de {} é {:.2f}'.format(n, n ** 0.5))
print('O quadrado de {} é {}'.format(n, n ** 2))